sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t natnathou/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true natnathou/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'dockeriser-react-nginx'
  env: 'Dockeriserreactnginx-env'
  bucket-name: 'elasticbeanstalk-us-east-2-819989340981'
  bucket-path: 'docker-with-travis'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
